package core

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"math/big"
	"net/http"
	"strings"
	"time"
)

// KeyPair holds a private/public key pair used in circuit inputs.
type KeyPair struct {
	PrivateKey *big.Int
	PublicKey  *big.Int
}

// ProofResult holds the output of a proof generation function.
type ProofResult struct {
	Proof           []string
	Statement       []*big.Int
	NumberOfInputs  int
	NumberOfOutputs int

	// CipherText holds the ML-KEM capsule for each output note (one per output,
	// 1088 bytes each). Published on-chain alongside the commitment so the
	// recipient can run Decapsulate to recover saltB.
	CipherText [][]byte

	// EncTxData holds the AEAD-encrypted payload for each output note
	// (one per output). Contains tokenId||amount encrypted with saltB via
	// ChaCha20-Poly1305. An authentication failure means the note is not
	// addressed to the scanning key.
	EncTxData [][]byte

	// SaltsOut holds the output salt for each output note (one per output).
	// Populated by non-KEM flows (e.g. ERC721, ERC1155) where the salt is
	// generated by the prover and must be handed to the recipient out-of-band
	// so they can later spend the note.
	SaltsOut []*big.Int

	// AuditData is populated by auditor proof functions. It carries the data
	// needed for the auditor to decrypt and verify the encrypted audit trail.
	AuditData *AuditEncryptionData
}

// AuditEncryptionData holds the encryption parameters produced during an auditor proof.
// AuthKeyX/Y is the Poseidon encryption key (= MulPointEscalar(auditorPubKey, random)).
// The auditor can decrypt by calling AuditorDecrypt(AuthKeyX, AuthKeyY, Nonce, Encrypted, RealLength).
type AuditEncryptionData struct {
	AuthKeyX   *big.Int   // StAuditorAuthKey[0] — store alongside the proof
	AuthKeyY   *big.Int   // StAuditorAuthKey[1]
	Nonce      *big.Int   // StAuditorNonce
	Encrypted  []*big.Int // StAuditorEncryptedValues
	RealLength int        // number of meaningful plaintext values
}

// ContractStatement converts the interleaved statement produced by the Go prover
// into the non-interleaved layout expected by the Solidity vault contracts.
//
// Go prover (interleaved):
//
//	[msg, tree0, root0, null0, tree1, root1, null1, …, cmt0, cmt1]
//
// Contract checkReceiptConditions (non-interleaved):
//
//	[msg, tree0..nIn-1, root0..nIn-1, null0..nIn-1, cmt0..nOut-1]
//
// The commitment elements are already last in both layouts so only the
// per-input triplets (tree, root, null) need to be de-interleaved.
func (r *ProofResult) ContractStatement() []*big.Int {
	nIn := r.NumberOfInputs
	nOut := r.NumberOfOutputs
	out := make([]*big.Int, 1+3*nIn+nOut)

	// message
	out[0] = r.Statement[0]

	// de-interleave: statement[1 + i*3 .. 1 + i*3 + 2] = (tree[i], root[i], null[i])
	for i := 0; i < nIn; i++ {
		base := 1 + i*3
		out[1+i]       = r.Statement[base]   // treeNumbers[i]
		out[1+nIn+i]   = r.Statement[base+1] // merkleRoots[i]
		out[1+2*nIn+i] = r.Statement[base+2] // nullifiers[i]
	}

	// commitments — same relative order, just placed after the three flat arrays
	for i := 0; i < nOut; i++ {
		out[1+3*nIn+i] = r.Statement[1+3*nIn+i]
	}

	return out
}

// GnarkClient is an HTTP client for the gnark proof generation server.
type GnarkClient struct {
	BaseURL string
	Client  *http.Client
}

// ProofResponse is the standard response from most proof endpoints.
type ProofResponse struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
}

// PrivateMintProofResponse is the response from the /proof/privateMint endpoint.
type PrivateMintProofResponse struct {
	Proof        []string `json:"proof"`
	PublicSignal []string `json:"publicSignal"`
}

// NewGnarkClient creates a new GnarkClient with the given base URL.
// If baseURL is empty, it defaults to http://localhost:8081.
func NewGnarkClient(baseURL string) *GnarkClient {
	if baseURL == "" {
		baseURL = "http://localhost:8081"
	}
	return &GnarkClient{
		BaseURL: baseURL,
		Client: &http.Client{
			Timeout: 60 * time.Second,
		},
	}
}

// PostProof sends a POST request with a JSON payload to the given endpoint
// and returns the raw response body.
func (c *GnarkClient) PostProof(endpoint string, data interface{}) ([]byte, error) {
	jsonData, err := json.Marshal(data)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request body: %w", err)
	}

	url := c.BaseURL + endpoint
	resp, err := c.Client.Post(url, "application/json", bytes.NewReader(jsonData))
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(body))
	}

	log.Printf("Response from %s: %s", endpoint, string(body))
	return body, nil
}

// GnarkProver dispatches proof generation based on the zkeyPath string.
func (c *GnarkClient) GnarkProver(circuitInput map[string]interface{}, zkeyPath string) (*ProofResponse, *PrivateMintProofResponse, error) {
	switch {
	case strings.Contains(zkeyPath, "OwnershipErc721"):
		resp, err := c.Erc721Proof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "JoinSplitErc20"):
		resp, err := c.Erc20Proof(circuitInput, zkeyPath)
		return resp, nil, err
	case strings.Contains(zkeyPath, "OwnershipErc1155NonFungibleWithAuditor"):
		resp, err := c.Erc1155NonFungibleWithAuditorProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "OwnershipErc1155NonFungible"):
		resp, err := c.Erc1155NonFungibleProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "JoinSplitErc1155WithAuditor"):
		resp, err := c.Erc1155FungibleAuditorMapProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "JoinSplitErc1155"):
		resp, err := c.Erc1155FungibleProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "AuctionInit_Auditor"):
		resp, err := c.AuctionInitAuditorProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "AuctionInit"):
		resp, err := c.AuctionInitMapProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "AuctionBid_Auditor"):
		resp, err := c.AuctionBidAuditorProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "AuctionBid"):
		resp, err := c.AuctionBidMapProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "AuctionPrivateOpening"):
		resp, err := c.AuctionPrivateOpeningProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "AuctionNotWinningBid"):
		log.Println("AuctionNotWinningBidProof")
		resp, err := c.AuctionNotWinningBidProof(circuitInput)
		return resp, nil, err
	case strings.Contains(zkeyPath, "PrivateMint"):
		resp, err := c.PrivateMintProof(circuitInput)
		return nil, resp, err
	default:
		return nil, nil, fmt.Errorf("unknown zkeyPath: %s", zkeyPath)
	}
}

// --- helper functions (used by legacy map-based provers) ---

// toString converts any value to its string representation.
func toString(v interface{}) string {
	if v == nil {
		return ""
	}
	return fmt.Sprintf("%v", v)
}

// toStringSlice converts a slice of any type to a slice of strings.
func toStringSlice(v interface{}) []string {
	items := toInterfaceSlice(v)
	result := make([]string, len(items))
	for i, item := range items {
		result[i] = toString(item)
	}
	return result
}

// toNestedStringSlice converts a [][]interface{} to [][]string.
func toNestedStringSlice(v interface{}) [][]string {
	outer := toInterfaceSlice(v)
	result := make([][]string, len(outer))
	for i, inner := range outer {
		result[i] = toStringSlice(inner)
	}
	return result
}

// toInterfaceSlice converts any slice-like value to []interface{}.
func toInterfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	if s, ok := v.([]interface{}); ok {
		return s
	}
	if s, ok := v.([]string); ok {
		result := make([]interface{}, len(s))
		for i, item := range s {
			result[i] = item
		}
		return result
	}
	return nil
}

// splitIntoTwo splits a slice at the given index.
func splitIntoTwo(arr []interface{}, splitAt int) ([]interface{}, []interface{}) {
	if len(arr) <= splitAt {
		return arr, nil
	}
	return arr[:splitAt], arr[splitAt:]
}

// ChunkArray splits a slice into chunks of the given size.
func ChunkArray(arr []interface{}, chunkSize int) [][]interface{} {
	if chunkSize <= 0 {
		chunkSize = 8
	}

	var result [][]interface{}
	for i := 0; i < len(arr); i += chunkSize {
		chunk := make([]interface{}, chunkSize)
		for j := 0; j < chunkSize; j++ {
			if i+j < len(arr) {
				chunk[j] = arr[i+j]
			}
		}
		result = append(result, chunk)
	}
	return result
}

// SplitPathElements splits inputs["wt_pathElements"] into chunks of 8.
func SplitPathElements(inputs map[string]interface{}) [][]interface{} {
	elements := toInterfaceSlice(inputs["wt_pathElements"])
	return ChunkArray(elements, 8)
}
