const assert = require("assert");
const { chromium, launchOpts, freshPage, clickAndWait, setupProtocol, BASE_URL } = require("./_env.cjs");

const ids = ["institutional", "retail", "dvp", "auctions"];
let passed = 0;
function pass(name) { passed += 1; console.log(`  PASS  ${name}`); }

(async () => {
  const browser = await chromium.launch({ ...launchOpts, headless: true });
  try {
    const { context, page } = await freshPage(browser, "institutional");

    assert.equal(await page.locator('[data-command="deploy"]').isVisible(), true);
    assert.equal(await page.locator("[data-action]").count(), 0);
    assert.equal(await page.locator('[data-executing-entity="System operator"]').isVisible(), true);
    pass("strict setup gating starts at operator deployment");

    await clickAndWait(page, '[data-command="deploy"]');
    assert.equal(await page.locator('[data-command="auditor"]').isVisible(), true);
    assert.equal(await page.locator('[data-executing-entity="Auditor"]').isVisible(), true);
    assert.equal(await page.locator('[data-auditor-keygen="empty"]').count(), 1);
    assert.equal(await page.locator('[data-command="auditor-confirm"]').count(), 0);
    await page.evaluate(() => window.__ENYGMA_DEMO__.engine.confirmAuditorKey("institutional"));
    assert.equal(await page.evaluate(() => window.__ENYGMA_DEMO__.state().protocols.institutional.stage), 1);
    await clickAndWait(page, '[data-command="auditor"]');
    const auditorState = await page.evaluate(() => window.__ENYGMA_DEMO__.state().protocols.institutional);
    assert.equal(auditorState.stage, 1);
    assert.equal(auditorState.auditorConfigured, false);
    assert.equal(await page.locator('[data-executing-entity="Auditor"]').isVisible(), true);
    assert.equal(await page.locator('[data-auditor-key="secret"] .key-value').innerText(), auditorState.auditor.privateKey);
    assert.equal(await page.locator('[data-auditor-key="public"] .key-value').innerText(), auditorState.auditor.publicKey);
    assert.equal(await page.locator('[data-auditor-keygen="complete"] .key-output.is-ready').count(), 2);
    assert.equal(await page.locator('[data-command="configure"]').count(), 0);
    assert.equal(await page.locator('[data-command="auditor"]').count(), 0);
    const desktopViewport = page.viewportSize();
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, "auditor workspace fits mobile width");
    await page.setViewportSize(desktopViewport);
    pass("auditor generates both keys and stays in its private workspace for review");
    await page.evaluate(async () => {
      await window.__ENYGMA_DEMO__.engine.generateAuditorKey("institutional");
      await window.__ENYGMA_DEMO__.engine.configureAuditor("institutional");
    });
    assert.deepEqual(await page.evaluate(() => window.__ENYGMA_DEMO__.state().protocols.institutional), auditorState);
    await page.reload();
    assert.equal(await page.locator('[data-executing-entity="Auditor"]').isVisible(), true);
    assert.equal(await page.locator('[data-auditor-key="secret"] .key-value').innerText(), auditorState.auditor.privateKey);
    assert.equal(await page.locator('[data-auditor-key="public"] .key-value').innerText(), auditorState.auditor.publicKey);
    pass("generated auditor keypair survives reload and cannot skip review or regenerate");
    await clickAndWait(page, '[data-command="auditor-confirm"]');
    assert.equal(await page.locator('[data-executing-entity="System operator"]').isVisible(), true);
    assert.equal(await page.locator(".auditor-public-handoff .key-value").innerText(), auditorState.auditor.publicKey);
    assert(!(await page.locator("body").innerText()).includes(auditorState.auditor.privateKey));
    assert.equal(await page.locator('[data-auditor-key="secret"]').count(), 0);
    pass("operator receives only the auditor public key after the explicit handoff");
    await clickAndWait(page, '[data-command="configure"]');
    assert.equal(await page.locator('[data-executing-entity="Protocol participant"]').isVisible(), true);
    await clickAndWait(page, '[data-command="identity-spend-secret"]');
    let state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.identityCeremony.phase, "spend_secret");
    assert(state.identityCeremony.spendPrivateKey.startsWith("spend_sk_"));
    assert.equal(state.identityCeremony.viewPrivateKey, null);
    assert.equal(state.identityCeremony.spendPublicKey, null);
    assert.equal(state.identities.length, 0);
    assert.equal(await page.locator(".secret-output.is-ready").count(), 1);
    pass("spend secret key is generated first");

    await clickAndWait(page, '[data-command="identity-spend-public"]');
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.identityCeremony.phase, "spend_public");
    assert(state.identityCeremony.spendPublicKey.startsWith("spend_pk_"));
    assert.equal(state.identityCeremony.viewPrivateKey, null);
    assert.equal(await page.locator(".public-output.is-ready").count(), 1);
    assert.match(await page.locator(".spend-card").innerText(), /Poseidon\(sk_spend, sk_spend\) mod ℓ/);
    pass("spend public key follows its hash operation");

    await clickAndWait(page, '[data-command="identity-view-secret"]');
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.identityCeremony.phase, "view_secret");
    assert(state.identityCeremony.viewPrivateKey.startsWith("mlkem_sk_"));
    assert.equal(state.identityCeremony.viewPublicKey, null);
    assert.equal(await page.locator(".secret-output.is-ready").count(), 2);
    pass("view secret key follows the completed spend keypair");

    await clickAndWait(page, '[data-command="identity-view-public"]');
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.identityCeremony.phase, "complete");
    assert(state.identityCeremony.viewPublicKey.startsWith("mlkem_pk_"));
    assert.equal(await page.locator(".public-output.is-ready").count(), 2);
    assert.match(await page.locator(".view-card").innerText(), /ML-KEM-768 key generation/i);
    await clickAndWait(page, '[data-command="identity-confirm"]');
    assert.equal(await page.locator('[data-executing-entity="Registering participant"]').isVisible(), true);
    pass("view public key completes the sequential ceremony");
    pass("ordered deploy, auditor key, configuration, and identity stages");

    assert.equal(await page.locator(".registry-table tbody tr").count(), 1);
    assert.equal(await page.locator('[data-party-row="1"]').count(), 0);
    assert.deepEqual(await page.locator(".registry-table th").allTextContents(), ["Participant", "Spend public key", "View public key", "1 · Register keys", "2 · Share with auditor"]);
    assert.equal(await page.locator('[data-party-row="0"] [data-key="spend"] code').textContent(), state.identities[0].institutionalSpendPublicKey);
    assert.equal(await page.locator('[data-party-row="0"] [data-key="view"] code').textContent(), state.identities[0].viewPublicKey);
    await clickAndWait(page, '[data-command="register-participant-keys"]');
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.institutional.registrations.length, 1);
    assert.equal(state.protocols.institutional.registrations[0].policy, "long_term");
    assert.equal(state.protocols.institutional.registrations[0].auditEnvelope, null);
    assert.equal(await page.locator(".registry-table tbody tr").count(), 1);
    assert.equal(await page.locator('[data-command="share-participant-key"]').isVisible(), true);
    pass("participant public keys register before auditor sharing");
    await clickAndWait(page, '[data-command="share-participant-key"]');
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert(state.protocols.institutional.registrations[0].auditEnvelope);
    assert.equal(await page.locator('[data-command="register-others"]').isVisible(), true);
    await clickAndWait(page, '[data-command="register-others"]');
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.deepEqual(state.protocols.institutional.registrations.map(r => r.partyId), Array.from({ length: 10 }, (_, i) => `party-${i}`));
    assert(state.protocols.institutional.registrations.every(r => r.policy === "long_term" && r.auditEnvelope));
    assert.equal(await page.locator(".network-registry tbody tr").count(), 10);
    assert.equal(await page.locator("#setupWorkspace").isHidden(), true);
    assert.equal(await page.locator("#progress").isHidden(), true);
    assert.equal(await page.locator(".scenario-page > article").count(), 1);
    assert.equal(await page.locator(".scenario-page [data-action]").count(), 0);
    pass("participant shares with auditor before other parties register");
    pass("completed registration becomes its own walkthrough screen");

    for (const id of ids.slice(1)) await setupProtocol(page, id);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    for (const id of ids) {
      const registrations = state.protocols[id].registrations;
      assert.equal(registrations.length, 10);
      registrations.forEach((registration, index) => {
        assert.equal(registration.spendPublicKey, id === "institutional" ? state.identities[index].institutionalSpendPublicKey : state.identities[index].spendPublicKey);
        assert.equal(registration.viewPublicKey, state.identities[index].viewPublicKey);
      });
      assert(registrations.every(r => r.policy === "long_term" && r.auditEnvelope));
      assert.equal(state.protocols[id].selectiveRegulator.name, "Additional regulator");
      await page.goto(`${BASE_URL}/#/${id}`);
      assert.equal(await page.locator(".network-registry tbody tr").count(), 10);
      assert.equal(await page.locator('.network-registry [data-public-party-row="0"] .registry-key').count(), 2);
      await page.locator(".protocol-primitives summary").click();
      const primitives = await page.locator(".protocol-primitives").innerText();
      assert.match(primitives, /ML-KEM-768/);
      assert.match(primitives, /Groth16 over BN254/);
      if (id === "institutional") {
        assert.match(primitives, /Poseidon\(sk_spend, sk_spend\) mod ℓ/);
        assert.match(primitives, /Pedersen on BabyJubJub/);
      } else {
        assert.match(primitives, /Poseidon\(sk_spend\)/);
        assert.match(primitives, /Poseidon\(pk_spend, salt, amount, token_id\)/);
        assert.match(primitives, /HKDF-SHA256/);
        assert.match(primitives, /AES-256-GCM/);
      }
      if (id === "dvp") assert.match(primitives, /ChaCha20-Poly1305/);
      if (id === "retail") assert.match(primitives, /Poseidon\(block_number, pk_spend, ss_field\)/);
    }
    assert.notEqual(state.identities[0].spendPublicKey, state.identities[0].institutionalSpendPublicKey);
    pass("registries use the protocol-specific Poseidon spend key and shared ML-KEM-768 view key");
    pass("the public participant registry remains visible throughout every protocol");
    pass("all participants use long-term auditing in every protocol");
    assert(ids.every(id => state.protocols[id].leaves.length === 0));
    pass("every commitment tree starts empty with no seeded leaves");

    const auditors = ids.map(id => state.protocols[id].auditor.publicKey);
    assert.equal(new Set(auditors).size, 4);
    assert.equal(state.protocols.retail.transactions.length, 0);
    await page.goto(`${BASE_URL}/#/institutional/channels`);
    assert.equal(await page.locator(".scenario-page > article").count(), 1);
    assert.equal(await page.locator('.scenario-progress [aria-current="step"] strong').innerText(), "Pairwise channels");
    assert.equal(await page.locator('.scenario-page [data-action="payment"]').count(), 0);
    await page.click('[data-action="channels"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.institutional.flow.channels, true);
    assert.equal(state.protocols.institutional.flow.channelPairs.length, 45);
    assert.equal(new Set(state.protocols.institutional.flow.channelPairs.map(pair => `${pair.leftPartyId}:${pair.rightPartyId}`)).size, 45);
    assert.equal(await page.locator(".channel-cell-pair.established").count(), 45);
    assert.match(await page.locator(".channel-network-card").innerText(), /45 \/ 45 ESTABLISHED/);
    assert.equal(state.protocols.retail.transactions.length, 0);
    pass("institutional matrix exposes all 45 unique pairwise channels");
    pass("protocol setup and ledger state remain independent");

    await page.goto(`${BASE_URL}/#/institutional/policy`);
    await page.click('[data-action="freeze"]'); await page.waitForTimeout(40);
    assert.equal((await page.evaluate(() => window.__ENYGMA_DEMO__.state())).protocols.institutional.flow.frozen, true);
    await page.click('[data-action="resume"]'); await page.waitForTimeout(40);
    await page.goto(`${BASE_URL}/#/institutional/payment`);
    await page.click('[data-action="payment"]'); await page.waitForTimeout(40);
    await page.goto(`${BASE_URL}/#/institutional/chain`);
    assert.match(await page.locator(".scenario-page").innerText(), /Pedersen commitments on BabyJubJub/);
    assert.equal(await page.locator(".commitment-tree").count(), 0);
    assert.equal((await page.evaluate(() => window.__ENYGMA_DEMO__.state())).protocols.institutional.leaves.length, 0);
    pass("institutional payment, freeze, and recovery paths");

    await page.goto(`${BASE_URL}/#/retail/payment`);
    assert.equal(await page.locator('[data-action="payment"]').isDisabled(), true);
    assert.equal(await page.getByText(/direct tagged channel|rotating recipient tag/i).count(), 0);
    await page.goto(`${BASE_URL}/#/retail/private-tags`);
    assert.equal(await page.locator(".tag-mode-card").count(), 4);
    assert.equal(await page.locator(".tag-registry-table tbody tr").count(), 10);
    assert.equal(await page.locator('.tag-registry-table [data-tag-party-row="1"] [data-key="spend"] code').textContent(), state.protocols.retail.registrations[1].spendPublicKey);
    assert.equal(await page.locator('.tag-registry-table [data-tag-party-row="1"] [data-key="view"] code').textContent(), state.protocols.retail.registrations[1].viewPublicKey);
    assert.equal(await page.locator('.tag-mode-card[data-retail-tag-mode="full"][aria-pressed="true"]').count(), 1);
    assert.equal(await page.locator(".tag-registry-table .bitmap-membership.included").count(), 10);
    await page.click('[data-retail-tag-mode="none"]');
    assert.equal(await page.locator(".tag-registry-table .bitmap-membership.included").count(), 1);
    await page.click('[data-retail-tag-mode="subset"]');
    assert.equal(await page.locator(".tag-registry-table .bitmap-membership.included").count(), 4);
    await page.click('[data-retail-tag-mode="rift"]');
    assert.equal(await page.locator(".tag-registry-table .bitmap-membership.included").count(), 8);
    assert.equal(await page.locator('[data-tag-party-row="1"] [data-retail-exclusion]').count(), 0);
    await page.click('[data-retail-tag-mode="full"]');
    await page.click('[data-action="configure-tags"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.deepEqual(state.protocols.retail.flow.retailRecipient, {
      partyId: state.protocols.retail.registrations[1].partyId,
      name: state.protocols.retail.registrations[1].name,
      spendPublicKey: state.protocols.retail.registrations[1].spendPublicKey,
      viewPublicKey: state.protocols.retail.registrations[1].viewPublicKey
    });
    assert.equal(state.protocols.retail.flow.retailTagChannel.mode, "full");
    assert.equal(state.protocols.retail.flow.retailTagChannel.bitmap, "1111111111");
    assert.equal(state.protocols.retail.flow.retailTagChannel.candidateIndices.length, 10);
    assert.match(await page.locator(".channel-record").innerText(), /Full privacy[\s\S]*1111111111/i);
    pass("retail private-tag table visualizes None, Subset, Rift, and Full bitmap membership");
    await page.goto(`${BASE_URL}/#/retail/payment`);
    assert.equal(await page.getByText(/Retrieve Atlas Bank keys|Retrieve the recipient’s public keys/i).count(), 0);
    assert.match(await page.locator(".registry-binding-visual").innerText(), /Atlas Bank[\s\S]*pk_spend[\s\S]*Recipient commitment[\s\S]*pk_view[\s\S]*Encrypted note data/i);
    assert.match(await page.locator(".payment-construction").innerText(), /Registry binding[\s\S]*Commitments[\s\S]*Groth16 proof[\s\S]*Private tag/);
    await page.fill("#retailPaymentAmount", "45");
    await page.click('[data-action="payment"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    const retailPayment = state.protocols.retail.transactions.find(tx => tx.type === "payment");
    assert.equal(retailPayment.from, "party-0");
    assert.equal(retailPayment.to, "party-1");
    assert.equal(retailPayment.encryptedPayload.amount, 45);
    assert(retailPayment.privateTag.startsWith("tag_"));
    assert.equal(state.protocols.retail.leaves.filter(leaf => leaf.sourceTxId === retailPayment.id).length, 2);
    await page.goto(`${BASE_URL}/#/retail/scan`);
    assert.equal(await page.locator(".scan-table tbody tr").count(), 10);
    await page.click('[data-action="scan"]'); await page.waitForTimeout(40);
    assert.equal(await page.locator(".scan-table tr.scan-match").count(), 1);
    assert.match(await page.locator(".scan-table tr.scan-match").innerText(), /Atlas Bank[\s\S]*Note opened and commitment matched/i);
    pass("retail payment binds registry keys visually and candidate wallets process the published bitmap");

    await page.goto(`${BASE_URL}/#/dvp/terms-proposal`);
    assert.match(await page.locator(".dvp-parties").innerText(), /Boreal Markets[\s\S]*Atlas Bank/);
    assert.equal(await page.locator('[data-action="propose-terms"]').isDisabled(), true);
    await page.goto(`${BASE_URL}/#/dvp/seller-holdings`);
    await page.fill("#dvpMintSecurityAmount", "1800");
    await page.click('[data-action="mint-security"]'); await page.waitForTimeout(40);
    await page.goto(`${BASE_URL}/#/dvp/seller-asset`);
    await page.fill("#dvpShieldSecurityAmount", "250");
    await page.click('[data-action="shield-security"]'); await page.waitForTimeout(40);
    await page.fill("#dvpShieldSecurityAmount", "950");
    await page.click('[data-action="shield-security"]'); await page.waitForTimeout(40);
    assert.equal(await page.locator('[data-tree-asset="RAYLS-BOND-2030"] .leaf-node.owned-leaf').count(), 2);
    assert.equal(await page.locator('[data-tree-asset="RAYLS-BOND-2030"] .leaf-node[data-owned="true"]').count(), 2);
    await page.goto(`${BASE_URL}/#/dvp/buyer-holdings`);
    await page.fill("#dvpMintCashAmount", "12000000");
    await page.click('[data-action="mint-cash"]'); await page.waitForTimeout(40);
    await page.goto(`${BASE_URL}/#/dvp/terms-proposal`);
    assert.equal(await page.locator('[data-action="propose-terms"]').isDisabled(), true);
    await page.goto(`${BASE_URL}/#/dvp/buyer-cash`);
    await page.fill("#dvpShieldCashAmount", "2462500");
    await page.click('[data-action="shield-cash"]'); await page.waitForTimeout(40);
    await page.fill("#dvpShieldCashAmount", "5537500");
    await page.click('[data-action="shield-cash"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.dvp.flow.sellerPublicSecurity, 600);
    assert.equal(state.protocols.dvp.flow.sellerShieldedSecurity, 1200);
    assert.equal(state.protocols.dvp.flow.buyerPublicCash, 4000000);
    assert.equal(state.protocols.dvp.flow.buyerShieldedCash, 8000000);
    assert.equal(state.protocols.dvp.flow.dvpTerms.status, "draft");
    assert.equal(state.protocols.dvp.leaves.length, 4);
    assert.equal(state.protocols.dvp.trees["RAYLS-BOND-2030"].leafIds.length, 2);
    assert.equal(state.protocols.dvp.trees.USD.leafIds.length, 2);
    assert.notEqual(state.protocols.dvp.trees["RAYLS-BOND-2030"].root, state.protocols.dvp.trees.USD.root);
    assert(state.protocols.dvp.leaves.every(leaf => state.protocols.dvp.transactions.some(tx => tx.id === leaf.sourceTxId && ["shield-security", "shield-cash"].includes(tx.type))));
    assert.equal(state.protocols.dvp.notes.length, 4);
    assert.equal(new Set(state.protocols.dvp.notes.map(note => note.leafId)).size, 4);
    assert.equal(new Set(state.protocols.dvp.notes.map(note => note.salt)).size, 4);
    assert(state.protocols.dvp.notes.every(note => state.protocols.dvp.leaves.some(leaf => leaf.id === note.leafId && leaf.commitment === note.commitment)));
    assert.equal(await page.locator(".owned-note").count(), 2);
    assert.equal(await page.locator('[data-tree-asset="USD"] .leaf-node.owned-leaf').count(), 2);
    assert.match(await page.locator(".note-construction-card").innerText(), /One shielding operation → one private note → one leaf[\s\S]*Leaf 0[\s\S]*Leaf 1/i);
    pass("repeated partial shielding creates a new leaf for every submission");
    assert.equal(await page.locator(".shielding-network [data-traffic]").count(), 1);
    assert.equal(await page.locator('[data-tree-asset="USD"] .leaf-node').count(), 2);
    const cashRootBeforeTraffic = await page.locator('[data-tree-asset="USD"]').getAttribute("data-merkle-root");
    const bondRootBeforeTraffic = state.protocols.dvp.trees["RAYLS-BOND-2030"].root;
    assert.equal(cashRootBeforeTraffic, state.protocols.dvp.trees.USD.root);
    await page.check(".shielding-network [data-traffic]");
    await page.waitForTimeout(3550);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert(state.protocols.dvp.leaves.length > 4);
    assert(state.protocols.dvp.transactions.some(tx => tx.type === "background-shield"));
    assert(state.protocols.dvp.leaves.every(leaf => state.protocols.dvp.transactions.some(tx => tx.id === leaf.sourceTxId)));
    assert.notEqual(state.protocols.dvp.trees.USD.root, cashRootBeforeTraffic);
    assert.equal(state.protocols.dvp.trees["RAYLS-BOND-2030"].root, bondRootBeforeTraffic);
    assert.equal(await page.locator('[data-tree-asset="USD"] .leaf-node.new-path').count(), 1);
    assert.equal(await page.locator('[data-tree-asset="USD"] .leaf-node.owned-leaf').count(), 2);
    assert.equal(await page.locator('[data-tree-asset="USD"] .leaf-node.new-path.owned-leaf').count(), 0);
    await page.uncheck(".shielding-network [data-traffic]");
    pass("cash traffic updates only the cash tree while the bond root remains unchanged");

    await page.goto(`${BASE_URL}/#/dvp/terms-proposal`);
    assert.equal(await page.locator('.terms-form [data-term-leg="security"] #dvpSecurityNote').count(), 1);
    assert.equal(await page.locator('.terms-form [data-term-leg="cash"] #dvpCashNote').count(), 1);
    assert.equal(await page.locator("#dvpSecurityNote option").count(), 2);
    assert.equal(await page.locator("#dvpCashNote option").count(), 2);
    const selectedSecurityNoteId = await page.locator("#dvpSecurityNote").inputValue();
    const selectedCashNoteId = await page.locator("#dvpCashNote").inputValue();
    await page.fill("#dvpExpiryBlocks", "40");
    await page.click('[data-action="propose-terms"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.deepEqual({ status: state.protocols.dvp.flow.dvpTerms.status, securityId: state.protocols.dvp.flow.dvpTerms.securityId, quantity: state.protocols.dvp.flow.dvpTerms.quantity, cashAmount: state.protocols.dvp.flow.dvpTerms.cashAmount, expiryBlocks: state.protocols.dvp.flow.dvpTerms.expiryBlocks, securityInputNoteId: state.protocols.dvp.flow.dvpTerms.securityInputNoteId, cashInputNoteId: state.protocols.dvp.flow.dvpTerms.cashInputNoteId }, { status: "proposed", securityId: "RAYLS-BOND-2030", quantity: 250, cashAmount: 2462500, expiryBlocks: 40, securityInputNoteId: selectedSecurityNoteId, cashInputNoteId: selectedCashNoteId });
    await page.goto(`${BASE_URL}/#/dvp/terms-acceptance`);
    assert.equal(await page.locator(".terms-form").count(), 0);
    assert.equal(await page.locator(".acceptance-sheet").count(), 1);
    assert.match(await page.locator(".acceptance-sheet").innerText(), /Buyer commits[\s\S]*2,462,500 USD[\s\S]*Buyer receives[\s\S]*250 RAYLS-BOND-2030/i);
    await page.click('[data-action="accept-terms"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.dvp.flow.dvpTerms.status, "agreed");
    assert.equal(state.protocols.dvp.flow.dvpTransfer, null);
    assert.equal(state.protocols.dvp.flow.cashLocked, false);
    assert.equal(await page.locator('[data-action="instantiate-transfer"]').isEnabled(), true);
    await page.click('[data-action="instantiate-transfer"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    const firstDvpTransferId = state.protocols.dvp.flow.dvpTransfer.id;
    assert(firstDvpTransferId.startsWith("dvp_"));
    assert(state.protocols.dvp.flow.dvpTransfer.termsCommitment.startsWith("terms_"));
    assert.equal(state.protocols.dvp.flow.dvpTransfer.status, "awaiting_counterparty");
    assert.equal(state.protocols.dvp.flow.cashLocked, true);
    assert.equal(state.protocols.dvp.flow.securityLocked, false);
    assert.equal(state.protocols.dvp.notes.find(note => note.id === selectedCashNoteId).status, "locked");
    assert.equal(await page.locator(".transfer-identity").count(), 1);
    pass("DvP term sheet groups securities and cash under their respective legs");
    pass("buyer acceptance and transfer initiation are distinct actions on one approval screen");
    await page.goto(`${BASE_URL}/#/dvp/timeout`);
    assert.equal(await page.locator('[data-action="timeout"]').isEnabled(), true);
    await page.click('[data-action="timeout"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.dvp.flow.settlement, "reverted");
    assert.equal(state.protocols.dvp.flow.dvpTransfer.status, "reverted");
    assert.equal(state.protocols.dvp.flow.securityLocked, false);
    assert.equal(state.protocols.dvp.flow.cashLocked, false);
    assert.equal(state.protocols.dvp.notes.find(note => note.id === selectedCashNoteId).status, "unspent");
    pass("initiating the DvP immediately exposes the one-sided timeout path");

    await page.click('[data-action="instantiate-transfer"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.notEqual(state.protocols.dvp.flow.dvpTransfer.id, firstDvpTransferId);
    assert.equal(state.protocols.dvp.flow.cashLocked, true);
    assert.equal(state.protocols.dvp.flow.securityLocked, false);
    await page.goto(`${BASE_URL}/#/dvp/settlement`);
    await page.click('[data-action="lock-security"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.dvp.flow.settlement, "settled");
    assert.equal(state.protocols.dvp.flow.securityLocked, true);
    assert.equal(state.protocols.dvp.flow.cashLocked, true);
    assert.equal(state.protocols.dvp.flow.dvpTransfer.status, "settled");
    assert.equal(state.protocols.dvp.transactions.some(tx => tx.type === "atomic-settlement"), true);
    assert.equal(state.protocols.dvp.flow.buyerPrivateSecurity, 250);
    assert.equal(state.protocols.dvp.flow.sellerPrivateCash, 2462500);
    assert.equal(state.protocols.dvp.flow.sellerShieldedSecurity, 950);
    assert.equal(state.protocols.dvp.flow.buyerShieldedCash, 5537500);
    assert.equal(state.protocols.dvp.notes.find(note => note.id === selectedSecurityNoteId).status, "spent");
    assert.equal(state.protocols.dvp.notes.find(note => note.id === selectedCashNoteId).status, "spent");
    assert.equal(state.protocols.dvp.notes.filter(note => note.origin === "dvp_output" && note.transferId === state.protocols.dvp.flow.dvpTransfer.id).length, 2);
    const settledLegCommitments = state.protocols.dvp.transactions.filter(tx => tx.encryptedPayload?.scope === "dvp_leg" && tx.encryptedPayload.transferId === state.protocols.dvp.flow.dvpTransfer.id).map(tx => tx.encryptedPayload.commitment).sort();
    const settlementTx = state.protocols.dvp.transactions.find(tx => tx.type === "atomic-settlement");
    assert.deepEqual(state.protocols.dvp.leaves.filter(leaf => leaf.sourceTxId === settlementTx.id).map(leaf => leaf.commitment).sort(), settledLegCommitments);
    await page.goto(`${BASE_URL}/#/dvp/timeout`);
    assert.equal(await page.locator('[data-action="timeout"]').count(), 0);
    assert.equal(await page.locator('[data-action="instantiate-transfer"]').count(), 0);
    assert.match(await page.locator(".scenario-page").innerText(), /This transfer settled[\s\S]*exactly one leg is locked/i);
    assert.equal(await page.locator('[data-action="settle"]').count(), 0);
    pass("second DvP leg lock settles atomically with no timeout or manual settlement");

    await page.goto(`${BASE_URL}/#/dvp/audit`);
    assert.equal(await page.locator(".audit-perspective").count(), 3);
    assert.equal(await page.locator('[data-share]').count(), 0);
    assert.match(await page.locator(".audit-registration-status").innerText(), /Auditor access established during registration[\s\S]*10 encrypted participant view keys/i);
    assert.doesNotMatch(await page.locator(".audit-perspective.outsider").innerText(), /Atlas Bank|Boreal Markets|2,462,500|250 RAYLS/i);
    assert.match(await page.locator(".audit-perspective.participant").innerText(), /250 RAYLS-BOND-2030[\s\S]*cannot open/i);
    assert.doesNotMatch(await page.locator(".audit-perspective.participant").innerText(), /2,462,500 USD/i);
    assert.match(await page.locator(".audit-perspective.auditor").innerText(), /250 RAYLS-BOND-2030[\s\S]*2,462,500 USD/i);
    assert.equal(state.protocols.dvp.disclosures.length, 0);
    assert.equal(await page.locator('.scenario-progress a[href="#/dvp/traffic"], .scenario-progress a[href="#/dvp/chain"]').count(), 0);
    assert.equal(await page.locator('.scenario-progress a[href="#/dvp/unshield"]').getByText(/Optional unshield/i).count(), 1);
    pass("DvP audit view uses registration-time access and keeps the outsider view opaque");

    await page.goto(`${BASE_URL}/#/auctions/auctioneer`);
    assert.match(await page.locator(".scenario-page").innerText(), /auctioneer—not the operator—generates/i);
    await page.click('[data-action="auctioneer"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert(state.protocols.auctions.flow.auction.auctioneerKey.publicKey.startsWith("mlkem_pk_"));
    assert.notEqual(state.protocols.auctions.flow.auction.auctioneerKey.publicKey, state.protocols.auctions.auditor.publicKey);
    await page.goto(`${BASE_URL}/#/auctions/auctioneer-registration`);
    assert.match(await page.locator(".registration-binding").innerText(), /auction_class_a_01/i);
    await page.click('[data-action="register-auctioneer"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.auctions.flow.auction.auctioneerRegistered, true);
    pass("auctioneer generates its own key and the operator binds it to one auction");

    await page.goto(`${BASE_URL}/#/auctions/mint-asset`);
    assert.equal(await page.locator("#auctionAssetQuantity").count(), 1);
    await page.fill("#auctionAssetQuantity", "25");
    await page.click('[data-action="mint-nft"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.auctions.flow.auction.assetQuantity, 25);
    assert.equal(state.protocols.auctions.flow.auction.sellerPublicNft, 25);
    assert.match(await page.locator(".nft-certificate").innerText(), /Shares represented[\s\S]*25/i);
    await page.goto(`${BASE_URL}/#/auctions/list-asset`);
    await page.fill("#auctionDuration", "14");
    await page.click('[data-action="list-asset"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.auctions.flow.auction.assetType, "Class A Share");
    assert.equal(state.protocols.auctions.flow.auction.assetTokenId, "CLASS-A-0042");
    assert.equal(state.protocols.auctions.flow.auction.assetQuantity, 25);
    assert.equal(state.protocols.auctions.flow.auction.biddingDuration, 14);
    assert.equal(state.protocols.auctions.trees["Class A Share"].leafIds.length, 1);
    assert.equal(state.protocols.auctions.notes.find(note => note.origin === "auction_asset").amount, 25);
    assert.match(await page.locator(".listing-visibility").innerText(), /Bidders are shown[\s\S]*Class A Share[\s\S]*details remain private/i);
    pass("seller chooses the Class A certificate quantity before listing it with a timeout");

    await page.goto(`${BASE_URL}/#/auctions/fund-bidder`);
    await page.fill("#auctionMintCashAmount", "1000");
    await page.click('[data-action="mint-cash"]'); await page.waitForTimeout(40);
    await page.goto(`${BASE_URL}/#/auctions/shield-bidder`);
    await page.fill("#auctionShieldCashAmount", "650");
    await page.click('[data-action="shield-cash"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    const auctionFundingNote = state.protocols.auctions.notes.find(note => note.origin === "auction_funding");
    assert.equal(auctionFundingNote.amount, 650);
    assert.equal(await page.locator('[data-tree-asset="USD"] .owned-leaf').count(), 1);
    await page.goto(`${BASE_URL}/#/auctions/submit-bid`);
    assert.match(await page.locator(".bid-target").innerText(), /Class A Share[\s\S]*certificate ID, quantity, and metadata withheld/i);
    assert.equal(await page.locator("#auctionBidAmount").count(), 1);
    await page.fill("#auctionBidAmount", "600");
    await page.click('[data-action="submit-bid"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    const auctionChangeNote = state.protocols.auctions.notes.find(note => note.origin === "auction_change");
    assert.equal(state.protocols.auctions.flow.auction.bids[0].amount, 600);
    assert.equal(state.protocols.auctions.notes.find(note => note.id === auctionFundingNote.id).status, "spent");
    assert.equal(auctionChangeNote.amount, 50);
    assert.equal(auctionChangeNote.status, "unspent");
    assert.equal(state.protocols.auctions.flow.auction.privateCash, 50);
    assert(state.protocols.auctions.leaves.some(leaf => leaf.id === auctionChangeNote.leafId));
    assert.match(await page.locator(".sealed-bid-receipt").innerText(), /Your private bid[\s\S]*600 USD[\s\S]*Private change[\s\S]*50 USD/i);
    assert.doesNotMatch(await page.locator(".bid-target").innerText(), /CLASS-A-0042/);
    pass("bidder chooses a partial bid and receives the unspent note value as private change");

    await page.goto(`${BASE_URL}/#/auctions/bidding-window`);
    await page.click('[data-action="collect-bids"]'); await page.waitForTimeout(40);
    assert.equal(await page.locator(".opaque-bid-stream > div").count(), 5);
    assert.doesNotMatch(await page.locator(".opaque-bid-stream").innerText(), /\b(?:600|610|575|540|420) USD\b/);
    await page.click('[data-action="close-bidding"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.auctions.flow.auction.status, "closed");
    assert.equal(state.protocols.auctions.flow.auction.blocksRemaining, 0);
    await page.goto(`${BASE_URL}/#/auctions/bid-review`);
    assert.doesNotMatch(await page.locator(".auction-view.public").innerText(), /\b(?:600|610|575|540|420) USD\b/);
    assert.match(await page.locator(".private-bid-table").innerText(), /600 USD[\s\S]*610 USD/i);
    assert.match(await page.locator(".scenario-page").innerText(), /Auctioneer[\s\S]*Auditor/i);
    pass("timeout closes bidding before auctioneer and auditor open all valid bids");

    await page.goto(`${BASE_URL}/#/auctions/winner-proof`);
    assert.match(await page.locator(".proof-statement").innerText(), /Out of all valid bids, this specific bid has the highest amount/i);
    assert.equal(await page.locator(".proof-bid-table tr.winning-bid").count(), 1);
    assert.match(await page.locator(".proof-bid-table tr.winning-bid").innerText(), /Delta Custody[\s\S]*610 USD[\s\S]*Highest valid/i);
    assert.equal(await page.locator(".zk-circuit .circuit-flow section").count(), 4);
    assert.match(await page.locator(".zk-circuit").innerText(), /amount\* ≥ amountᵢ[\s\S]*winning commitment \+ π[\s\S]*No amount is a public output/i);
    await page.click('[data-action="prove-winner"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.auctions.flow.auction.winnerProof.privateWinningAmount, 610);
    assert.equal(state.protocols.auctions.flow.auction.winnerProof.validBidCount, 5);
    assert.equal(state.protocols.auctions.flow.auction.winnerProof.winnerPartyId, "party-4");
    assert.doesNotMatch(await page.locator(".winner-announcement").innerText(), /610/);
    assert.match(await page.locator(".winner-announcement").innerText(), /Winning amount remains private/i);
    pass("auctioneer announces only the winning commitment and highest-valid-bid proof");

    await page.goto(`${BASE_URL}/#/auctions/settlement`);
    await page.click('[data-action="challenge"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.auctions.flow.auction.challengeOpen, true);
    await page.click('[data-action="settle"]'); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.auctions.flow.auction.status, "settled");
    assert.equal(state.protocols.auctions.flow.auction.challengeOpen, false);
    assert.equal(state.protocols.auctions.flow.auction.settlement.winnerPartyId, "party-4");
    assert.equal(state.protocols.auctions.notes.find(note => note.id === auctionFundingNote.id).status, "spent");
    assert.equal(state.protocols.auctions.notes.find(note => note.id === auctionChangeNote.id).status, "unspent");
    assert.equal(state.protocols.auctions.notes.find(note => note.origin === "auction_recovery" && note.ownerPartyId === "party-0").amount, 600);
    assert.equal(state.protocols.auctions.flow.auction.privateCash, 650);
    assert.equal(state.protocols.auctions.notes.filter(note => note.origin === "auction_output").length, 2);
    assert.equal(state.protocols.auctions.notes.filter(note => note.origin === "auction_recovery").length, 4);
    assert.equal(state.protocols.auctions.trees["Class A Share"].leafIds.length, 2);
    assert.equal(state.protocols.auctions.notes.find(note => note.origin === "auction_output" && note.assetId === "Class A Share").amount, 25);
    assert.equal(state.protocols.auctions.trees.USD.leafIds.length, 7);
    assert.match(await page.locator(".settlement-outputs").innerText(), /Public winning amount[\s\S]*Not disclosed/i);
    assert.equal(await page.locator('[data-auction-perspective="public"][aria-selected="true"]').count(), 1);
    assert.equal(await page.locator(".public-perspective .owned-leaf").count(), 0);
    assert.doesNotMatch(await page.locator(".public-perspective").innerText(), /Atlas Bank|Boreal Markets|Delta Custody|controls this leaf/i);
    assert.match(await page.locator(".public-perspective").innerText(), /ownership hidden/i);
    await page.click('[data-auction-perspective="wallet"]');
    assert.equal(await page.locator(".wallet-perspective .owned-leaf").count(), 2);
    assert.match(await page.locator(".wallet-perspective").innerText(), /recognized by this wallet/i);
    assert.doesNotMatch(await page.locator(".wallet-perspective").innerText(), /controls this leaf/i);
    await page.click('[data-auction-perspective="auditor"]');
    assert.equal(await page.locator(".auditor-output-table tbody tr").count(), 6);
    assert.match(await page.locator(".auditor-output-table").innerText(), /Delta Custody[\s\S]*25 Class A Share[\s\S]*Boreal Markets[\s\S]*610 USD/i);
    await page.goto(`${BASE_URL}/#/auctions/audit`);
    assert.equal(await page.locator('[data-share]').count(), 0);
    assert.match(await page.locator(".auction-visibility-matrix").innerText(), /Public network[\s\S]*Cannot open any bid amount[\s\S]*Auditor[\s\S]*Cannot bid, choose, or spend/i);
    pass("auction settlement separates neutral public, private wallet, and authorized auditor views");

    await page.goto(`${BASE_URL}/#/retail/traffic`);
    const before = await page.evaluate(() => ({ tx: window.__ENYGMA_DEMO__.state().protocols.retail.transactions.length, leaves: window.__ENYGMA_DEMO__.state().protocols.retail.leaves.length }));
    await page.waitForTimeout(3550);
    const off = await page.evaluate(() => ({ tx: window.__ENYGMA_DEMO__.state().protocols.retail.transactions.length, leaves: window.__ENYGMA_DEMO__.state().protocols.retail.leaves.length }));
    assert.deepEqual(off, before);
    await page.check("[data-traffic]");
    await page.waitForTimeout(3550);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert(state.protocols.retail.transactions.length > before.tx);
    const txIds = new Set(state.protocols.retail.transactions.map(tx => tx.id));
    assert(state.protocols.retail.leaves.every(leaf => txIds.has(leaf.sourceTxId)));
    await page.uncheck("[data-traffic]");
    pass("traffic off is stable and traffic on creates only transaction-backed leaves");

    const firstTx = state.protocols.retail.transactions[0].id;
    await page.goto(`${BASE_URL}/#/retail/audit`);
    await page.click(`[data-share="${firstTx}"]`); await page.waitForTimeout(40);
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert(state.protocols.retail.disclosures.some(item => item.txId === firstTx && item.scope === "single transaction" && item.recipient === "Additional regulator"));
    pass("selective disclosure grants one transaction key to the additional regulator");

    await page.reload();
    await page.waitForFunction(() => window.__ENYGMA_DEMO__);
    assert.equal((await page.evaluate(() => window.__ENYGMA_DEMO__.state())).protocols.retail.registrations.length, 10);
    assert.equal(new URL(page.url()).hash, "#/retail/audit");
    pass("hash routes and session restoration retain progress");

    const savedProgress = await page.evaluate(() => {
      const saved = window.__ENYGMA_DEMO__.state();
      for (const identity of [...saved.identities, saved.identityCeremony]) delete identity.institutionalSpendPublicKey;
      for (const registration of saved.protocols.institutional.registrations) {
        registration.spendPublicKey = saved.identities.find(identity => identity.id === registration.partyId).spendPublicKey;
      }
      for (const protocol of Object.values(saved.protocols)) {
        protocol.auditor.algorithm = "ML-KEM";
        for (const tx of protocol.transactions) {
          if (tx.encryptedPayload) {
            delete tx.encryptedPayload.encryption;
            tx.encryptedPayload.encryptedFields = ["salt", "token_id", "amount"];
          }
        }
      }
      sessionStorage.setItem("enygma-demo-state-v12", JSON.stringify(saved));
      return saved.protocols.retail.transactions.length;
    });
    await page.reload();
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.retail.transactions.length, savedProgress);
    assert.equal(state.protocols.institutional.registrations[0].spendPublicKey, state.identities[0].institutionalSpendPublicKey);
    assert.notEqual(state.protocols.institutional.registrations[0].spendPublicKey, state.protocols.retail.registrations[0].spendPublicKey);
    assert.equal(state.protocols.retail.auditor.algorithm, "ML-KEM-768");
    assert.match(await page.locator(".auditable-transaction").first().innerText(), /AES-256-GCM · encrypted: token_id · amount/);
    pass("older sessions adopt the corrected primitives without losing protocol progress");

    await page.evaluate(() => window.__ENYGMA_DEMO__.engine.resetProtocol("retail"));
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.protocols.retail.registrations.length, 0);
    assert.equal(state.identities.length, 10);
    await page.evaluate(() => window.__ENYGMA_DEMO__.engine.resetAll());
    state = await page.evaluate(() => window.__ENYGMA_DEMO__.state());
    assert.equal(state.identities.length, 0);
    assert(ids.every(id => state.protocols[id].contracts.length === 0));
    pass("protocol and entire-demo resets have distinct scope");

    await page.goto(`${BASE_URL}/#/choose`);
    assert.equal(await page.locator("#chooser h1").innerText(), "Choose a protocol to bring online.");
    assert.equal(await page.locator(".skip-link").count(), 1);
    assert.equal(await page.locator("nav[aria-label=Protocols]").count(), 1);
    await context.close();
    const mobile = await freshPage(browser, "choose", { width: 390, height: 844 });
    const overflow = await mobile.page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
    assert.equal(overflow, false);
    assert.equal(await mobile.page.locator(".protocol-card").count(), 4);
    await mobile.context.close();
    pass("accessible landmarks and responsive mobile layout");

    console.log(`\n${passed} browser behavior checks passed.`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
