block
columns 1

 block:ID
 block: commits
    C_1["$$Commit_{1}$$"]
    C_dots["$$\dots$$"]
    C_k["$$Commit_{k}$$"]
end 

block: tags
    t_1["$$t_{1}$$"]
    t_dots["$$\dots$$"]
    t_k["$$t_{k}$$"]
end

block: ciphertexts

    ctxt_1["$$ctxt_{1}$$"]
    ctxt_dots["$$\dots$$"]
    ctxt_k["$$ctxt_{k}$$"]

end

    zkp["$$\pi$$"]

end
